/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutAnimejoyPagesImport } from './routes/_layout/_animejoy-pages'
import { Route as LayoutAnimejoyPagesIndexImport } from './routes/_layout/_animejoy-pages/index'
import { Route as LayoutAnimejoyPagesCategoryIndexImport } from './routes/_layout/_animejoy-pages/$category/index'
import { Route as LayoutAnimejoyPagesCategoryAnimeIdIndexImport } from './routes/_layout/_animejoy-pages/$category/$animeId/index'
import { Route as LayoutAnimejoyPagesCategoryPagePageIndexImport } from './routes/_layout/_animejoy-pages/$category/page/$page/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAnimejoyPagesRoute = LayoutAnimejoyPagesImport.update({
  id: '/_animejoy-pages',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAnimejoyPagesIndexRoute = LayoutAnimejoyPagesIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutAnimejoyPagesRoute,
} as any)

const LayoutAnimejoyPagesCategoryIndexRoute =
  LayoutAnimejoyPagesCategoryIndexImport.update({
    path: '/$category/',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

const LayoutAnimejoyPagesCategoryAnimeIdIndexRoute =
  LayoutAnimejoyPagesCategoryAnimeIdIndexImport.update({
    path: '/$category/$animeId/',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

const LayoutAnimejoyPagesCategoryPagePageIndexRoute =
  LayoutAnimejoyPagesCategoryPagePageIndexImport.update({
    path: '/$category/page/$page/',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_animejoy-pages': {
      id: '/_layout/_animejoy-pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAnimejoyPagesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_animejoy-pages/': {
      id: '/_layout/_animejoy-pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAnimejoyPagesIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/$category/': {
      id: '/_layout/_animejoy-pages/$category/'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/$category/$animeId/': {
      id: '/_layout/_animejoy-pages/$category/$animeId/'
      path: '/$category/$animeId'
      fullPath: '/$category/$animeId'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryAnimeIdIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/$category/page/$page/': {
      id: '/_layout/_animejoy-pages/$category/page/$page/'
      path: '/$category/page/$page'
      fullPath: '/$category/page/$page'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryPagePageIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAnimejoyPagesRoute: LayoutAnimejoyPagesRoute.addChildren({
      LayoutAnimejoyPagesIndexRoute,
      LayoutAnimejoyPagesCategoryIndexRoute,
      LayoutAnimejoyPagesCategoryAnimeIdIndexRoute,
      LayoutAnimejoyPagesCategoryPagePageIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_animejoy-pages"
      ]
    },
    "/_layout/_animejoy-pages": {
      "filePath": "_layout/_animejoy-pages.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_animejoy-pages/",
        "/_layout/_animejoy-pages/$category/",
        "/_layout/_animejoy-pages/$category/$animeId/",
        "/_layout/_animejoy-pages/$category/page/$page/"
      ]
    },
    "/_layout/_animejoy-pages/": {
      "filePath": "_layout/_animejoy-pages/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/$category/": {
      "filePath": "_layout/_animejoy-pages/$category/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/$category/$animeId/": {
      "filePath": "_layout/_animejoy-pages/$category/$animeId/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/$category/page/$page/": {
      "filePath": "_layout/_animejoy-pages/$category/page/$page/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    }
  }
}
ROUTE_MANIFEST_END */
