/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithLoaderImport } from './routes/_with-loader'
import { Route as ShikijoyAuthCallbackImport } from './routes/shikijoy.auth-callback'
import { Route as WithLoaderLayoutImport } from './routes/_with-loader/_layout'
import { Route as WithLoaderLayoutAnimejoyPagesImport } from './routes/_with-loader/_layout/_animejoy-pages'
import { Route as WithLoaderLayoutAnimejoyPagesIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/index'
import { Route as WithLoaderLayoutAnimejoyPagesCategoryImport } from './routes/_with-loader/_layout/_animejoy-pages/$category'
import { Route as WithLoaderLayoutAnimejoyPagesNewsIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/news/index'
import { Route as WithLoaderLayoutAnimejoyPagesCategoryIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/$category/index'
import { Route as WithLoaderLayoutAnimejoyPagesPagePageIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/page/$page/index'
import { Route as WithLoaderLayoutAnimejoyPagesNewsIdIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/news/$id/index'
import { Route as WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/$category/$showId/index'
import { Route as WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexImport } from './routes/_with-loader/_layout/_animejoy-pages/$category/page/$page/index'

// Create/Update Routes

const WithLoaderRoute = WithLoaderImport.update({
  id: '/_with-loader',
  getParentRoute: () => rootRoute,
} as any)

const ShikijoyAuthCallbackRoute = ShikijoyAuthCallbackImport.update({
  path: '/shikijoy/auth-callback',
  getParentRoute: () => rootRoute,
} as any)

const WithLoaderLayoutRoute = WithLoaderLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => WithLoaderRoute,
} as any)

const WithLoaderLayoutAnimejoyPagesRoute =
  WithLoaderLayoutAnimejoyPagesImport.update({
    id: '/_animejoy-pages',
    getParentRoute: () => WithLoaderLayoutRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesIndexRoute =
  WithLoaderLayoutAnimejoyPagesIndexImport.update({
    path: '/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesCategoryRoute =
  WithLoaderLayoutAnimejoyPagesCategoryImport.update({
    path: '/$category',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesNewsIndexRoute =
  WithLoaderLayoutAnimejoyPagesNewsIndexImport.update({
    path: '/news/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesCategoryIndexRoute =
  WithLoaderLayoutAnimejoyPagesCategoryIndexImport.update({
    path: '/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesCategoryRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesPagePageIndexRoute =
  WithLoaderLayoutAnimejoyPagesPagePageIndexImport.update({
    path: '/page/$page/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute =
  WithLoaderLayoutAnimejoyPagesNewsIdIndexImport.update({
    path: '/news/$id/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute =
  WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexImport.update({
    path: '/$showId/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesCategoryRoute,
  } as any)

const WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute =
  WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexImport.update({
    path: '/page/$page/',
    getParentRoute: () => WithLoaderLayoutAnimejoyPagesCategoryRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_with-loader': {
      id: '/_with-loader'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithLoaderImport
      parentRoute: typeof rootRoute
    }
    '/_with-loader/_layout': {
      id: '/_with-loader/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithLoaderLayoutImport
      parentRoute: typeof WithLoaderImport
    }
    '/shikijoy/auth-callback': {
      id: '/shikijoy/auth-callback'
      path: '/shikijoy/auth-callback'
      fullPath: '/shikijoy/auth-callback'
      preLoaderRoute: typeof ShikijoyAuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_with-loader/_layout/_animejoy-pages': {
      id: '/_with-loader/_layout/_animejoy-pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesImport
      parentRoute: typeof WithLoaderLayoutImport
    }
    '/_with-loader/_layout/_animejoy-pages/$category': {
      id: '/_with-loader/_layout/_animejoy-pages/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesImport
    }
    '/_with-loader/_layout/_animejoy-pages/': {
      id: '/_with-loader/_layout/_animejoy-pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesImport
    }
    '/_with-loader/_layout/_animejoy-pages/$category/': {
      id: '/_with-loader/_layout/_animejoy-pages/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryImport
    }
    '/_with-loader/_layout/_animejoy-pages/news/': {
      id: '/_with-loader/_layout/_animejoy-pages/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesNewsIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesImport
    }
    '/_with-loader/_layout/_animejoy-pages/$category/$showId/': {
      id: '/_with-loader/_layout/_animejoy-pages/$category/$showId/'
      path: '/$showId'
      fullPath: '/$category/$showId'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryImport
    }
    '/_with-loader/_layout/_animejoy-pages/news/$id/': {
      id: '/_with-loader/_layout/_animejoy-pages/news/$id/'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesNewsIdIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesImport
    }
    '/_with-loader/_layout/_animejoy-pages/page/$page/': {
      id: '/_with-loader/_layout/_animejoy-pages/page/$page/'
      path: '/page/$page'
      fullPath: '/page/$page'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesPagePageIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesImport
    }
    '/_with-loader/_layout/_animejoy-pages/$category/page/$page/': {
      id: '/_with-loader/_layout/_animejoy-pages/$category/page/$page/'
      path: '/page/$page'
      fullPath: '/$category/page/$page'
      preLoaderRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexImport
      parentRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryImport
    }
  }
}

// Create and export the route tree

interface WithLoaderLayoutAnimejoyPagesCategoryRouteChildren {
  WithLoaderLayoutAnimejoyPagesCategoryIndexRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryIndexRoute
  WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute
  WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute
}

const WithLoaderLayoutAnimejoyPagesCategoryRouteChildren: WithLoaderLayoutAnimejoyPagesCategoryRouteChildren =
  {
    WithLoaderLayoutAnimejoyPagesCategoryIndexRoute:
      WithLoaderLayoutAnimejoyPagesCategoryIndexRoute,
    WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute:
      WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute,
    WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute:
      WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute,
  }

const WithLoaderLayoutAnimejoyPagesCategoryRouteWithChildren =
  WithLoaderLayoutAnimejoyPagesCategoryRoute._addFileChildren(
    WithLoaderLayoutAnimejoyPagesCategoryRouteChildren,
  )

interface WithLoaderLayoutAnimejoyPagesRouteChildren {
  WithLoaderLayoutAnimejoyPagesCategoryRoute: typeof WithLoaderLayoutAnimejoyPagesCategoryRouteWithChildren
  WithLoaderLayoutAnimejoyPagesIndexRoute: typeof WithLoaderLayoutAnimejoyPagesIndexRoute
  WithLoaderLayoutAnimejoyPagesNewsIndexRoute: typeof WithLoaderLayoutAnimejoyPagesNewsIndexRoute
  WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute: typeof WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute
  WithLoaderLayoutAnimejoyPagesPagePageIndexRoute: typeof WithLoaderLayoutAnimejoyPagesPagePageIndexRoute
}

const WithLoaderLayoutAnimejoyPagesRouteChildren: WithLoaderLayoutAnimejoyPagesRouteChildren =
  {
    WithLoaderLayoutAnimejoyPagesCategoryRoute:
      WithLoaderLayoutAnimejoyPagesCategoryRouteWithChildren,
    WithLoaderLayoutAnimejoyPagesIndexRoute:
      WithLoaderLayoutAnimejoyPagesIndexRoute,
    WithLoaderLayoutAnimejoyPagesNewsIndexRoute:
      WithLoaderLayoutAnimejoyPagesNewsIndexRoute,
    WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute:
      WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute,
    WithLoaderLayoutAnimejoyPagesPagePageIndexRoute:
      WithLoaderLayoutAnimejoyPagesPagePageIndexRoute,
  }

const WithLoaderLayoutAnimejoyPagesRouteWithChildren =
  WithLoaderLayoutAnimejoyPagesRoute._addFileChildren(
    WithLoaderLayoutAnimejoyPagesRouteChildren,
  )

interface WithLoaderLayoutRouteChildren {
  WithLoaderLayoutAnimejoyPagesRoute: typeof WithLoaderLayoutAnimejoyPagesRouteWithChildren
}

const WithLoaderLayoutRouteChildren: WithLoaderLayoutRouteChildren = {
  WithLoaderLayoutAnimejoyPagesRoute:
    WithLoaderLayoutAnimejoyPagesRouteWithChildren,
}

const WithLoaderLayoutRouteWithChildren =
  WithLoaderLayoutRoute._addFileChildren(WithLoaderLayoutRouteChildren)

interface WithLoaderRouteChildren {
  WithLoaderLayoutRoute: typeof WithLoaderLayoutRouteWithChildren
}

const WithLoaderRouteChildren: WithLoaderRouteChildren = {
  WithLoaderLayoutRoute: WithLoaderLayoutRouteWithChildren,
}

const WithLoaderRouteWithChildren = WithLoaderRoute._addFileChildren(
  WithLoaderRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof WithLoaderLayoutAnimejoyPagesRouteWithChildren
  '/shikijoy/auth-callback': typeof ShikijoyAuthCallbackRoute
  '/$category': typeof WithLoaderLayoutAnimejoyPagesCategoryRouteWithChildren
  '/': typeof WithLoaderLayoutAnimejoyPagesIndexRoute
  '/$category/': typeof WithLoaderLayoutAnimejoyPagesCategoryIndexRoute
  '/news': typeof WithLoaderLayoutAnimejoyPagesNewsIndexRoute
  '/$category/$showId': typeof WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute
  '/news/$id': typeof WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute
  '/page/$page': typeof WithLoaderLayoutAnimejoyPagesPagePageIndexRoute
  '/$category/page/$page': typeof WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute
}

export interface FileRoutesByTo {
  '': typeof WithLoaderLayoutRouteWithChildren
  '/shikijoy/auth-callback': typeof ShikijoyAuthCallbackRoute
  '/': typeof WithLoaderLayoutAnimejoyPagesIndexRoute
  '/$category': typeof WithLoaderLayoutAnimejoyPagesCategoryIndexRoute
  '/news': typeof WithLoaderLayoutAnimejoyPagesNewsIndexRoute
  '/$category/$showId': typeof WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute
  '/news/$id': typeof WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute
  '/page/$page': typeof WithLoaderLayoutAnimejoyPagesPagePageIndexRoute
  '/$category/page/$page': typeof WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_with-loader': typeof WithLoaderRouteWithChildren
  '/_with-loader/_layout': typeof WithLoaderLayoutRouteWithChildren
  '/shikijoy/auth-callback': typeof ShikijoyAuthCallbackRoute
  '/_with-loader/_layout/_animejoy-pages': typeof WithLoaderLayoutAnimejoyPagesRouteWithChildren
  '/_with-loader/_layout/_animejoy-pages/$category': typeof WithLoaderLayoutAnimejoyPagesCategoryRouteWithChildren
  '/_with-loader/_layout/_animejoy-pages/': typeof WithLoaderLayoutAnimejoyPagesIndexRoute
  '/_with-loader/_layout/_animejoy-pages/$category/': typeof WithLoaderLayoutAnimejoyPagesCategoryIndexRoute
  '/_with-loader/_layout/_animejoy-pages/news/': typeof WithLoaderLayoutAnimejoyPagesNewsIndexRoute
  '/_with-loader/_layout/_animejoy-pages/$category/$showId/': typeof WithLoaderLayoutAnimejoyPagesCategoryShowIdIndexRoute
  '/_with-loader/_layout/_animejoy-pages/news/$id/': typeof WithLoaderLayoutAnimejoyPagesNewsIdIndexRoute
  '/_with-loader/_layout/_animejoy-pages/page/$page/': typeof WithLoaderLayoutAnimejoyPagesPagePageIndexRoute
  '/_with-loader/_layout/_animejoy-pages/$category/page/$page/': typeof WithLoaderLayoutAnimejoyPagesCategoryPagePageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/shikijoy/auth-callback'
    | '/$category'
    | '/'
    | '/$category/'
    | '/news'
    | '/$category/$showId'
    | '/news/$id'
    | '/page/$page'
    | '/$category/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/shikijoy/auth-callback'
    | '/'
    | '/$category'
    | '/news'
    | '/$category/$showId'
    | '/news/$id'
    | '/page/$page'
    | '/$category/page/$page'
  id:
    | '__root__'
    | '/_with-loader'
    | '/_with-loader/_layout'
    | '/shikijoy/auth-callback'
    | '/_with-loader/_layout/_animejoy-pages'
    | '/_with-loader/_layout/_animejoy-pages/$category'
    | '/_with-loader/_layout/_animejoy-pages/'
    | '/_with-loader/_layout/_animejoy-pages/$category/'
    | '/_with-loader/_layout/_animejoy-pages/news/'
    | '/_with-loader/_layout/_animejoy-pages/$category/$showId/'
    | '/_with-loader/_layout/_animejoy-pages/news/$id/'
    | '/_with-loader/_layout/_animejoy-pages/page/$page/'
    | '/_with-loader/_layout/_animejoy-pages/$category/page/$page/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WithLoaderRoute: typeof WithLoaderRouteWithChildren
  ShikijoyAuthCallbackRoute: typeof ShikijoyAuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  WithLoaderRoute: WithLoaderRouteWithChildren,
  ShikijoyAuthCallbackRoute: ShikijoyAuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_with-loader",
        "/shikijoy/auth-callback"
      ]
    },
    "/_with-loader": {
      "filePath": "_with-loader.tsx",
      "children": [
        "/_with-loader/_layout"
      ]
    },
    "/_with-loader/_layout": {
      "filePath": "_with-loader/_layout.tsx",
      "parent": "/_with-loader",
      "children": [
        "/_with-loader/_layout/_animejoy-pages"
      ]
    },
    "/shikijoy/auth-callback": {
      "filePath": "shikijoy.auth-callback.tsx"
    },
    "/_with-loader/_layout/_animejoy-pages": {
      "filePath": "_with-loader/_layout/_animejoy-pages.tsx",
      "parent": "/_with-loader/_layout",
      "children": [
        "/_with-loader/_layout/_animejoy-pages/$category",
        "/_with-loader/_layout/_animejoy-pages/",
        "/_with-loader/_layout/_animejoy-pages/news/",
        "/_with-loader/_layout/_animejoy-pages/news/$id/",
        "/_with-loader/_layout/_animejoy-pages/page/$page/"
      ]
    },
    "/_with-loader/_layout/_animejoy-pages/$category": {
      "filePath": "_with-loader/_layout/_animejoy-pages/$category.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages",
      "children": [
        "/_with-loader/_layout/_animejoy-pages/$category/",
        "/_with-loader/_layout/_animejoy-pages/$category/$showId/",
        "/_with-loader/_layout/_animejoy-pages/$category/page/$page/"
      ]
    },
    "/_with-loader/_layout/_animejoy-pages/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages"
    },
    "/_with-loader/_layout/_animejoy-pages/$category/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/$category/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages/$category"
    },
    "/_with-loader/_layout/_animejoy-pages/news/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/news/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages"
    },
    "/_with-loader/_layout/_animejoy-pages/$category/$showId/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/$category/$showId/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages/$category"
    },
    "/_with-loader/_layout/_animejoy-pages/news/$id/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/news/$id/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages"
    },
    "/_with-loader/_layout/_animejoy-pages/page/$page/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/page/$page/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages"
    },
    "/_with-loader/_layout/_animejoy-pages/$category/page/$page/": {
      "filePath": "_with-loader/_layout/_animejoy-pages/$category/page/$page/index.tsx",
      "parent": "/_with-loader/_layout/_animejoy-pages/$category"
    }
  }
}
ROUTE_MANIFEST_END */
