/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as ShikijoyAuthCallbackImport } from './routes/shikijoy.auth-callback'
import { Route as LayoutAnimejoyPagesImport } from './routes/_layout/_animejoy-pages'
import { Route as LayoutAnimejoyPagesIndexImport } from './routes/_layout/_animejoy-pages/index'
import { Route as LayoutAnimejoyPagesCategoryImport } from './routes/_layout/_animejoy-pages/$category'
import { Route as LayoutAnimejoyPagesNewsIndexImport } from './routes/_layout/_animejoy-pages/news/index'
import { Route as LayoutAnimejoyPagesCategoryIndexImport } from './routes/_layout/_animejoy-pages/$category/index'
import { Route as LayoutAnimejoyPagesPagePageIndexImport } from './routes/_layout/_animejoy-pages/page/$page/index'
import { Route as LayoutAnimejoyPagesNewsIdIndexImport } from './routes/_layout/_animejoy-pages/news/$id/index'
import { Route as LayoutAnimejoyPagesCategoryShowIdIndexImport } from './routes/_layout/_animejoy-pages/$category/$showId/index'
import { Route as LayoutAnimejoyPagesCategoryPagePageIndexImport } from './routes/_layout/_animejoy-pages/$category/page/$page/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const ShikijoyAuthCallbackRoute = ShikijoyAuthCallbackImport.update({
  path: '/shikijoy/auth-callback',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAnimejoyPagesRoute = LayoutAnimejoyPagesImport.update({
  id: '/_animejoy-pages',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAnimejoyPagesIndexRoute = LayoutAnimejoyPagesIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutAnimejoyPagesRoute,
} as any)

const LayoutAnimejoyPagesCategoryRoute =
  LayoutAnimejoyPagesCategoryImport.update({
    path: '/$category',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

const LayoutAnimejoyPagesNewsIndexRoute =
  LayoutAnimejoyPagesNewsIndexImport.update({
    path: '/news/',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

const LayoutAnimejoyPagesCategoryIndexRoute =
  LayoutAnimejoyPagesCategoryIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutAnimejoyPagesCategoryRoute,
  } as any)

const LayoutAnimejoyPagesPagePageIndexRoute =
  LayoutAnimejoyPagesPagePageIndexImport.update({
    path: '/page/$page/',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

const LayoutAnimejoyPagesNewsIdIndexRoute =
  LayoutAnimejoyPagesNewsIdIndexImport.update({
    path: '/news/$id/',
    getParentRoute: () => LayoutAnimejoyPagesRoute,
  } as any)

const LayoutAnimejoyPagesCategoryShowIdIndexRoute =
  LayoutAnimejoyPagesCategoryShowIdIndexImport.update({
    path: '/$showId/',
    getParentRoute: () => LayoutAnimejoyPagesCategoryRoute,
  } as any)

const LayoutAnimejoyPagesCategoryPagePageIndexRoute =
  LayoutAnimejoyPagesCategoryPagePageIndexImport.update({
    path: '/page/$page/',
    getParentRoute: () => LayoutAnimejoyPagesCategoryRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_animejoy-pages': {
      id: '/_layout/_animejoy-pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAnimejoyPagesImport
      parentRoute: typeof LayoutImport
    }
    '/shikijoy/auth-callback': {
      id: '/shikijoy/auth-callback'
      path: '/shikijoy/auth-callback'
      fullPath: '/shikijoy/auth-callback'
      preLoaderRoute: typeof ShikijoyAuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_animejoy-pages/$category': {
      id: '/_layout/_animejoy-pages/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/': {
      id: '/_layout/_animejoy-pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAnimejoyPagesIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/$category/': {
      id: '/_layout/_animejoy-pages/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryIndexImport
      parentRoute: typeof LayoutAnimejoyPagesCategoryImport
    }
    '/_layout/_animejoy-pages/news/': {
      id: '/_layout/_animejoy-pages/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof LayoutAnimejoyPagesNewsIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/$category/$showId/': {
      id: '/_layout/_animejoy-pages/$category/$showId/'
      path: '/$showId'
      fullPath: '/$category/$showId'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryShowIdIndexImport
      parentRoute: typeof LayoutAnimejoyPagesCategoryImport
    }
    '/_layout/_animejoy-pages/news/$id/': {
      id: '/_layout/_animejoy-pages/news/$id/'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof LayoutAnimejoyPagesNewsIdIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/page/$page/': {
      id: '/_layout/_animejoy-pages/page/$page/'
      path: '/page/$page'
      fullPath: '/page/$page'
      preLoaderRoute: typeof LayoutAnimejoyPagesPagePageIndexImport
      parentRoute: typeof LayoutAnimejoyPagesImport
    }
    '/_layout/_animejoy-pages/$category/page/$page/': {
      id: '/_layout/_animejoy-pages/$category/page/$page/'
      path: '/page/$page'
      fullPath: '/$category/page/$page'
      preLoaderRoute: typeof LayoutAnimejoyPagesCategoryPagePageIndexImport
      parentRoute: typeof LayoutAnimejoyPagesCategoryImport
    }
  }
}

// Create and export the route tree

interface LayoutAnimejoyPagesCategoryRouteChildren {
  LayoutAnimejoyPagesCategoryIndexRoute: typeof LayoutAnimejoyPagesCategoryIndexRoute
  LayoutAnimejoyPagesCategoryShowIdIndexRoute: typeof LayoutAnimejoyPagesCategoryShowIdIndexRoute
  LayoutAnimejoyPagesCategoryPagePageIndexRoute: typeof LayoutAnimejoyPagesCategoryPagePageIndexRoute
}

const LayoutAnimejoyPagesCategoryRouteChildren: LayoutAnimejoyPagesCategoryRouteChildren =
  {
    LayoutAnimejoyPagesCategoryIndexRoute:
      LayoutAnimejoyPagesCategoryIndexRoute,
    LayoutAnimejoyPagesCategoryShowIdIndexRoute:
      LayoutAnimejoyPagesCategoryShowIdIndexRoute,
    LayoutAnimejoyPagesCategoryPagePageIndexRoute:
      LayoutAnimejoyPagesCategoryPagePageIndexRoute,
  }

const LayoutAnimejoyPagesCategoryRouteWithChildren =
  LayoutAnimejoyPagesCategoryRoute._addFileChildren(
    LayoutAnimejoyPagesCategoryRouteChildren,
  )

interface LayoutAnimejoyPagesRouteChildren {
  LayoutAnimejoyPagesCategoryRoute: typeof LayoutAnimejoyPagesCategoryRouteWithChildren
  LayoutAnimejoyPagesIndexRoute: typeof LayoutAnimejoyPagesIndexRoute
  LayoutAnimejoyPagesNewsIndexRoute: typeof LayoutAnimejoyPagesNewsIndexRoute
  LayoutAnimejoyPagesNewsIdIndexRoute: typeof LayoutAnimejoyPagesNewsIdIndexRoute
  LayoutAnimejoyPagesPagePageIndexRoute: typeof LayoutAnimejoyPagesPagePageIndexRoute
}

const LayoutAnimejoyPagesRouteChildren: LayoutAnimejoyPagesRouteChildren = {
  LayoutAnimejoyPagesCategoryRoute:
    LayoutAnimejoyPagesCategoryRouteWithChildren,
  LayoutAnimejoyPagesIndexRoute: LayoutAnimejoyPagesIndexRoute,
  LayoutAnimejoyPagesNewsIndexRoute: LayoutAnimejoyPagesNewsIndexRoute,
  LayoutAnimejoyPagesNewsIdIndexRoute: LayoutAnimejoyPagesNewsIdIndexRoute,
  LayoutAnimejoyPagesPagePageIndexRoute: LayoutAnimejoyPagesPagePageIndexRoute,
}

const LayoutAnimejoyPagesRouteWithChildren =
  LayoutAnimejoyPagesRoute._addFileChildren(LayoutAnimejoyPagesRouteChildren)

interface LayoutRouteChildren {
  LayoutAnimejoyPagesRoute: typeof LayoutAnimejoyPagesRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnimejoyPagesRoute: LayoutAnimejoyPagesRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutAnimejoyPagesRouteWithChildren
  '/shikijoy/auth-callback': typeof ShikijoyAuthCallbackRoute
  '/$category': typeof LayoutAnimejoyPagesCategoryRouteWithChildren
  '/': typeof LayoutAnimejoyPagesIndexRoute
  '/$category/': typeof LayoutAnimejoyPagesCategoryIndexRoute
  '/news': typeof LayoutAnimejoyPagesNewsIndexRoute
  '/$category/$showId': typeof LayoutAnimejoyPagesCategoryShowIdIndexRoute
  '/news/$id': typeof LayoutAnimejoyPagesNewsIdIndexRoute
  '/page/$page': typeof LayoutAnimejoyPagesPagePageIndexRoute
  '/$category/page/$page': typeof LayoutAnimejoyPagesCategoryPagePageIndexRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutRouteWithChildren
  '/shikijoy/auth-callback': typeof ShikijoyAuthCallbackRoute
  '/': typeof LayoutAnimejoyPagesIndexRoute
  '/$category': typeof LayoutAnimejoyPagesCategoryIndexRoute
  '/news': typeof LayoutAnimejoyPagesNewsIndexRoute
  '/$category/$showId': typeof LayoutAnimejoyPagesCategoryShowIdIndexRoute
  '/news/$id': typeof LayoutAnimejoyPagesNewsIdIndexRoute
  '/page/$page': typeof LayoutAnimejoyPagesPagePageIndexRoute
  '/$category/page/$page': typeof LayoutAnimejoyPagesCategoryPagePageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_animejoy-pages': typeof LayoutAnimejoyPagesRouteWithChildren
  '/shikijoy/auth-callback': typeof ShikijoyAuthCallbackRoute
  '/_layout/_animejoy-pages/$category': typeof LayoutAnimejoyPagesCategoryRouteWithChildren
  '/_layout/_animejoy-pages/': typeof LayoutAnimejoyPagesIndexRoute
  '/_layout/_animejoy-pages/$category/': typeof LayoutAnimejoyPagesCategoryIndexRoute
  '/_layout/_animejoy-pages/news/': typeof LayoutAnimejoyPagesNewsIndexRoute
  '/_layout/_animejoy-pages/$category/$showId/': typeof LayoutAnimejoyPagesCategoryShowIdIndexRoute
  '/_layout/_animejoy-pages/news/$id/': typeof LayoutAnimejoyPagesNewsIdIndexRoute
  '/_layout/_animejoy-pages/page/$page/': typeof LayoutAnimejoyPagesPagePageIndexRoute
  '/_layout/_animejoy-pages/$category/page/$page/': typeof LayoutAnimejoyPagesCategoryPagePageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/shikijoy/auth-callback'
    | '/$category'
    | '/'
    | '/$category/'
    | '/news'
    | '/$category/$showId'
    | '/news/$id'
    | '/page/$page'
    | '/$category/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/shikijoy/auth-callback'
    | '/'
    | '/$category'
    | '/news'
    | '/$category/$showId'
    | '/news/$id'
    | '/page/$page'
    | '/$category/page/$page'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_animejoy-pages'
    | '/shikijoy/auth-callback'
    | '/_layout/_animejoy-pages/$category'
    | '/_layout/_animejoy-pages/'
    | '/_layout/_animejoy-pages/$category/'
    | '/_layout/_animejoy-pages/news/'
    | '/_layout/_animejoy-pages/$category/$showId/'
    | '/_layout/_animejoy-pages/news/$id/'
    | '/_layout/_animejoy-pages/page/$page/'
    | '/_layout/_animejoy-pages/$category/page/$page/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ShikijoyAuthCallbackRoute: typeof ShikijoyAuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ShikijoyAuthCallbackRoute: ShikijoyAuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/shikijoy/auth-callback"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_animejoy-pages"
      ]
    },
    "/_layout/_animejoy-pages": {
      "filePath": "_layout/_animejoy-pages.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_animejoy-pages/$category",
        "/_layout/_animejoy-pages/",
        "/_layout/_animejoy-pages/news/",
        "/_layout/_animejoy-pages/news/$id/",
        "/_layout/_animejoy-pages/page/$page/"
      ]
    },
    "/shikijoy/auth-callback": {
      "filePath": "shikijoy.auth-callback.tsx"
    },
    "/_layout/_animejoy-pages/$category": {
      "filePath": "_layout/_animejoy-pages/$category.tsx",
      "parent": "/_layout/_animejoy-pages",
      "children": [
        "/_layout/_animejoy-pages/$category/",
        "/_layout/_animejoy-pages/$category/$showId/",
        "/_layout/_animejoy-pages/$category/page/$page/"
      ]
    },
    "/_layout/_animejoy-pages/": {
      "filePath": "_layout/_animejoy-pages/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/$category/": {
      "filePath": "_layout/_animejoy-pages/$category/index.tsx",
      "parent": "/_layout/_animejoy-pages/$category"
    },
    "/_layout/_animejoy-pages/news/": {
      "filePath": "_layout/_animejoy-pages/news/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/$category/$showId/": {
      "filePath": "_layout/_animejoy-pages/$category/$showId/index.tsx",
      "parent": "/_layout/_animejoy-pages/$category"
    },
    "/_layout/_animejoy-pages/news/$id/": {
      "filePath": "_layout/_animejoy-pages/news/$id/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/page/$page/": {
      "filePath": "_layout/_animejoy-pages/page/$page/index.tsx",
      "parent": "/_layout/_animejoy-pages"
    },
    "/_layout/_animejoy-pages/$category/page/$page/": {
      "filePath": "_layout/_animejoy-pages/$category/page/$page/index.tsx",
      "parent": "/_layout/_animejoy-pages/$category"
    }
  }
}
ROUTE_MANIFEST_END */
